### ISSUE TITLE
腾讯内推 - 王肖的UT

### ISSUE THREAD

**Issue by wxdut** [wxdut/Gitalk-Issues-Wxdut#22]
https://wxdut.com/tencent.html

**Comment by wxdut** [comment]
有问题请留言评论。

**Comment by sunyuehang123** [comment]
收不到短信验证码怎么办呢

**Comment by wxdut** [comment]
1. 确认信息提交无误
2. 你的qq和微信有绑定提交的手机号么

> @sunyuehang123
> 收不到短信验证码怎么办呢

**Comment by sunyuehang123** [comment]
信息无误 还是没有收到验证码

**Comment by wxdut** [comment]
稍等，我在处理
> @sunyuehang123
> 信息无误 还是没有收到验证码

**Comment by liuxiaoxu6918** [comment]
您好，信息无误，是微信绑定手机号，收不到短信验证码该怎么办呀

**Comment by liuxiaoxu6918** [comment]
现在已经成功啦，非常感谢
